### ISSUE TITLE
Do you guys have any samples to upload

### ISSUE THREAD

**Issue by cliuxinxin** [nii-yamagishilab/self-attention-tacotron#5]
That will make it clear.

**Comment by TanUkkii007** [comment]
@cliuxinxin We can share some samples from LJSpeech. The Japanese corpus we used is not redistributable so we cannot provide Japanese samples in public.

**Comment by cliuxinxin** [comment]
I think it's a good idea. We all have LJspeech ：)

**Comment by TanUkkii007** [comment]
@cliuxinxin Sorry for the late response. I created audio samples from LJSpeech.
Audio quality of the samples is not good so I keep trying to improve it. In addition I will addd samples from other datasets in the future.
https://nii-yamagishilab.github.io/self-attention-tacotron-audio-samples/index.html

**Comment by cliuxinxin** [comment]
@TanUkkii007  Thank you for your reply. I have heard the samples sounds good. Any chance to implement the gst? I think add gst maybe let the sounds more nature.If I got some time can try your code on my own dataset , and give you some feedback. After Chinese spring festival. sank you for your work.

**Comment by TanUkkii007** [comment]
@cliuxinxin gst stands for global style tokens, right? I may implement it for a project but that project is not active so please do not expect too much.
I look forward to your feedback on your dataset.
